-- ─── Catalogue officiel SEGA 32X ──────────────────────────────────────────────
INSERT INTO retro_games (console_id, name, description)
SELECT rc.id, g.name, g.description
FROM retro_consoles rc
CROSS JOIN (VALUES
    ('After Burner Complete',
     'Prenez les commandes du F-14 Thunder Cat dans l''expérience d''arcade la plus fidèle jamais réalisée. Verrouillez vos cibles et déchaînez une puissance de feu dévastatrice à 60 images par seconde.'),
    ('BC Racers',
     'Lancez-vous dans une course préhistorique effrénée ! 32 circuits truffés de pièges où seule la loi du plus fort (et du plus rapide) compte.'),
    ('Blackthorne',
     'Incarnez Kyle Vlaros, un mercenaire armé d''un fusil à pompe, dans une quête pour reprendre son trône sur une planète sombre. Un action-platformer aux animations d''un réalisme saisissant.'),
    ('Brutal: Paws of Fury Special Edition',
     'Apprenez la philosophie des arts martiaux avec les maîtres les plus sauvages du monde animal. Une édition spéciale boostée par la puissance du 32X.'),
    ('Cosmic Carnage',
     'Le combat pour la survie commence aux confins de la galaxie. Utilisez des armures destructibles et des zooms spectaculaires pour écraser vos adversaires extraterrestres.'),
    ('Darxide',
     'L''humanité est au bord de l''extinction. Pilotez votre chasseur en 3D totale et détruisez les astéroïdes et les bases ennemies avant qu''il ne soit trop tard.'),
    ('Doom',
     'Le FPS légendaire arrive sur 32X. Explorez des bases martiennes infestées de démons avec une vitesse et une fluidité de calcul sans précédent.'),
    ('FIFA Soccer 96',
     'Entrez dans le stade virtuel ! Avec la technologie Virtual Stadium, vivez le football avec une liberté de mouvement totale et des statistiques réelles.'),
    ('Golf Magazine: 36 Holes Starring Fred Couples',
     'Le réalisme du golf professionnel entre vos mains. 36 trous numérisés et les conseils de Fred Couples pour parfaire votre swing.'),
    ('Knuckles'' Chaotix',
     'L''aventure Sonic la plus innovante ! Utilisez l''anneau de puissance pour créer un effet élastique entre vos personnages et atteindre des vitesses incroyables.'),
    ('Kolibri',
     'Incarnez le protecteur de la nature. Un shoot''em up unique aux graphismes luxuriants où vous devez sauver l''écosystème terrestre d''une menace de l''espace.'),
    ('Metal Head',
     'Prenez le contrôle d''une machine de guerre 3D texturée. Traversez des villes en proie au chaos et remplissez vos missions de pacification armée.'),
    ('Mortal Kombat II',
     'Rien n''est plus réel. Le kombat ultime revient avec des graphismes et des sons directement issus de la borne d''arcade. Finish Him !'),
    ('Motocross Championship',
     'La boue, la vitesse et la gloire. Affrontez les meilleurs pilotes mondiaux sur des circuits accidentés où chaque saut peut être le dernier.'),
    ('NBA Jam Tournament Edition',
     'Il est en feu ! Découvrez le basket-ball d''arcade avec des dunks qui défient les lois de la physique et des bonus délirants.'),
    ('NFL Quarterback Club',
     'Devenez une légende de la NFL. Gérez votre équipe et exécutez les jeux les plus complexes grâce à une précision graphique 32 bits.'),
    ('NHL 95',
     'Le hockey sur glace le plus rapide du monde. Des collisions brutales, des passes millimétrées et toute l''intensité de la NHL.'),
    ('Pitfall: The Mayan Adventure',
     'Aidez Harry Jr. à secourir son père dans la jungle maya. Un voyage périlleux aux animations de qualité cinéma.'),
    ('Primal Rage',
     'Les dieux primordiaux s''affrontent pour le contrôle de la Terre. Choisissez votre créature et dévorez vos fidèles pour regagner de l''énergie.'),
    ('RBI Baseball ''95',
     'La simulation de baseball la plus complète, incluant les vrais joueurs, les vraies équipes et des graphismes photo-réalistes.'),
    ('Sangokushi IV',
     'Écrivez l''histoire de la Chine ancienne. Un jeu de stratégie épique où la diplomatie est aussi tranchante que l''épée.'),
    ('Shadow Squadron',
     'Pilotez l''élite des chasseurs stellaires. Engagez-vous dans des combats spatiaux en 3D totale pour protéger la flotte de l''alliance.'),
    ('Space Harrier',
     'Bienvenue dans la Zone Fantastique ! Un classique de l''arcade porté avec une perfection absolue : volez, tirez et survivez.'),
    ('Spider-Man: Web of Fire',
     'L''homme-araignée fait équipe avec Daredevil pour déjouer les plans de l''HYDRA. Une action non-stop dans un univers de comics vibrant.'),
    ('Star Trek: Starfleet Academy',
     'Cadet, votre formation commence ici. Commandez les vaisseaux les plus célèbres de Starfleet dans des simulations de combat spatial intenses.'),
    ('Star Wars Arcade',
     'Que la Force soit avec vous. Revivez l''attaque de l''Étoile de la Mort et les batailles spatiales iconiques de la saga Star Wars en 3D.'),
    ('T-Mek',
     'Le sport de combat du futur. Pilotez des tanks aéroglisseurs et éliminez vos rivaux dans des arènes closes ultra-rapides.'),
    ('Tempo',
     'Laissez-vous emporter par le rythme ! Un jeu de plateforme musical où chaque mouvement de Tempo fait vibrer l''écran de couleurs.'),
    ('Toughman Contest',
     'Entrez sur le ring pour le tournoi de boxe amateur le plus sauvage. Esquivez, frappez et devenez le champion du Toughman.'),
    ('Virtua Fighter',
     'L''évolution du combat. La technologie d''arcade Model 1 arrive chez vous : des combats en 3D d''une fluidité et d''une technicité inégalées.'),
    ('Virtua Racing Deluxe',
     'La course automobile redéfinie. De nouvelles voitures, de nouveaux circuits et une sensation de vitesse que seul le 32X peut offrir.'),
    ('World Series Baseball ''95',
     'Le coup de circuit assuré. Une immersion totale sur le terrain avec des angles de vue dynamiques et une jouabilité parfaite.'),
    ('Wrestlemania: The Arcade Game',
     'C''est bien plus que du catch. C''est de l''action pure où les superstars de la WWF utilisent des pouvoirs surhumains pour la victoire.'),
    ('Zaxxon''s Motherbase 2000',
     'Le futur de Zaxxon est arrivé. Infiltrez la base mère ennemie dans ce shooter isométrique révolutionnaire mêlant 2D et 3D.'),
    -- ── Exclusifs Sega CD-32X ─────────────────────────────────────────────────
    ('Corpse Killer',
     'Une île tropicale, des zombies et votre fidèle fusil. Vivez un film d''action interactif avec une qualité d''image cinématographique 32 bits.'),
    ('Fahrenheit',
     'Face aux flammes, chaque seconde compte. Un thriller interactif où vous incarnez un pompier d''élite au cœur du brasier.'),
    ('Night Trap',
     'Protégez les invités de la maison à l''aide de caméras cachées et de pièges. La version ultime du jeu le plus controversé de l''histoire.'),
    ('Slam City with Scottie Pippen',
     'Défiez Scottie Pippen sur son propre terrain. Du basket-ball de rue en vidéo plein écran avec une réactivité instantanée.'),
    ('Supreme Warrior',
     'Maîtrisez les secrets du Kung-Fu. Affrontez des guerriers légendaires dans des combats filmés où seul votre timing vous sauvera.'),
    ('Surgical Strike',
     'Aux commandes d''un véhicule d''assaut high-tech, infiltrez le territoire ennemi pour une frappe chirurgicale. L''action FMV à son apogée.')
) AS g(name, description)
WHERE rc.name = '32X'
ON CONFLICT (console_id, name) DO NOTHING;