-- ─── Table des consoles rétro ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS retro_consoles (
    id           SERIAL PRIMARY KEY,
    name         TEXT NOT NULL,
    manufacturer TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_retro_consoles_name ON retro_consoles(name);

-- ─── Données ─────────────────────────────────────────────────────────────────
INSERT INTO retro_consoles (name, manufacturer) VALUES
    ('32X',                                         'SEGA'),
    ('3DO',                                         '3DO Company'),
    ('Amiga CD32',                                  'Commodore'),
    ('Atari 2600',                                  'Atari'),
    ('Atari 5200',                                  'Atari'),
    ('Atari 7800',                                  'Atari'),
    ('CD-i',                                        'Philips'),
    ('CDTV',                                        'Commodore'),
    ('ColecoVision',                                'CBS'),
    ('Dreamcast',                                   'SEGA'),
    ('FM Towns Marty',                              'Fujitsu'),
    ('Game Boy / Pocket / Color',                   'Nintendo'),
    ('Game Boy Advance / SP',                       'Nintendo'),
    ('GameCube',                                    'Nintendo'),
    ('Game Gear',                                   'SEGA'),
    ('Gizmondo',                                    'Tiger Telematics'),
    ('GP32',                                        'GamePark'),
    ('GX4000',                                      'Amstrad'),
    ('Intellivision',                               'Mattel'),
    ('Atari Jaguar',                                'Atari'),
    ('Atari Lynx',                                  'Atari'),
    ('Master System',                               'SEGA'),
    ('Mega-CD',                                     'SEGA'),
    ('Mega Drive / Genesis',                        'SEGA'),
    ('Konix Multi-System',                          'Konix'),
    ('Multi-Mega',                                  'SEGA'),
    ('N-Gage',                                      'Nokia'),
    ('PC Engine CD-ROM² / Super CD-ROM²',           'NEC'),
    ('Neo Geo AES',                                 'SNK'),
    ('Neo Geo CD / CDZ',                            'SNK'),
    ('Neo Geo Pocket',                              'SNK'),
    ('Neptune',                                     'SEGA'),
    ('NES / Famicom',                               'Nintendo'),
    ('Nintendo 64',                                 'Nintendo'),
    ('Nintendo DSi',                                'Nintendo'),
    ('Nomad',                                       'SEGA'),
    ('Magnavox Odyssey',                            'Magnavox'),
    ('Odyssey 2 / Videopac',                        'Philips'),
    ('PC Engine / CoreGrafx',                       'NEC'),
    ('PC Engine GT',                                'NEC'),
    ('PC Engine LT',                                'NEC'),
    ('Pippin',                                      'Bandai / Apple'),
    ('Playdia',                                     'Bandai'),
    ('PlayStation',                                 'Sony'),
    ('PlayStation 2',                               'Sony'),
    ('PSP',                                         'Sony'),
    ('Saturn',                                      'SEGA'),
    ('Sega Genesis 3',                              'SEGA'),
    ('SG-1000',                                     'SEGA'),
    ('Super Cassette Vision',                       'Yeno / Epoch'),
    ('Super NES / Super Famicom',                   'Nintendo'),
    ('SuperGrafx',                                  'NEC'),
    ('Atari XEGS',                                  'Atari'),
    ('Vectrex',                                     'Milton Bradley'),
    ('Virtual Boy',                                 'Nintendo'),
    ('WonderMega',                                  'SEGA'),
    ('WonderSwan',                                  'Bandai'),
    ('Xbox',                                        'Microsoft')
ON CONFLICT (name) DO NOTHING;
